/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Jorge
 */
public class EmployeeRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form registerView
     */
    public EmployeeRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_employeeName = new javax.swing.JLabel();
        lbl_tittle = new javax.swing.JLabel();
        lbl_employeePhone = new javax.swing.JLabel();
        lbl_employeeAddress = new javax.swing.JLabel();
        lbl_userData = new javax.swing.JLabel();
        lbl_employeeUserName = new javax.swing.JLabel();
        lbl_employeePassword = new javax.swing.JLabel();
        field_employeeName = new javax.swing.JTextField();
        field_employeeUserName = new javax.swing.JTextField();
        lbl_personalData = new javax.swing.JLabel();
        lbl_employePhoneLada = new javax.swing.JLabel();
        field_employeePhoneLada = new javax.swing.JTextField();
        lbl_employeePhoneNumber = new javax.swing.JLabel();
        field_employeePhoneNumber = new javax.swing.JTextField();
        lbl_employeeAddressStreet = new javax.swing.JLabel();
        lbl_employeeAddressColony = new javax.swing.JLabel();
        lbl_employeeAddressPostalCode = new javax.swing.JLabel();
        lbl_employeeAddressCross = new javax.swing.JLabel();
        field_employeeAddressStreet = new javax.swing.JTextField();
        field_employeeAddressColony = new javax.swing.JTextField();
        field_employeeAddressPostalCode = new javax.swing.JTextField();
        field_employeeAddressCross = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        field_employeeEmail = new javax.swing.JTextField();
        field_employeeUserPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        field_employeeRFC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_employeeName.setText("Nombre:");

        lbl_tittle.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        lbl_tittle.setText("Registro de Empleado");

        lbl_employeePhone.setText("Telefono");

        lbl_employeeAddress.setText("Direccion");

        lbl_userData.setText("Datos de usuario");

        lbl_employeeUserName.setText("Nombre de Usuario:");

        lbl_employeePassword.setText("Contraseña:");

        field_employeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeNameActionPerformed(evt);
            }
        });

        lbl_personalData.setText("Datos personales");

        lbl_employePhoneLada.setText("Clave lada:");

        field_employeePhoneLada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeePhoneLadaActionPerformed(evt);
            }
        });

        lbl_employeePhoneNumber.setText("digitos:");

        lbl_employeeAddressStreet.setText("calle:");

        lbl_employeeAddressColony.setText("colonia:");

        lbl_employeeAddressPostalCode.setText("numeroPostal:");

        lbl_employeeAddressCross.setText("cruzamientos:");

        field_employeeAddressPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeAddressPostalCodeActionPerformed(evt);
            }
        });

        btn_register.setText("Registrar");

        btn_cancel.setText("Cancelar");

        jLabel1.setText("Correo Electronico:");

        field_employeeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("RFC:");

        field_employeeRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeRFCActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/Employee 2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_employeeAddressColony)
                                .addGap(18, 18, 18)
                                .addComponent(field_employeeAddressColony, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_employeeAddressPostalCode)
                                .addGap(18, 18, 18)
                                .addComponent(field_employeeAddressPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_employeeAddressStreet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(field_employeeAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_tittle))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_employeeAddressCross)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field_employeeAddressCross, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_employeePhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(field_employeePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lbl_employePhoneLada)
                                .addGap(44, 44, 44)
                                .addComponent(field_employeePhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_employeePhone)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_employeeName)
                                        .addGap(18, 18, 18)
                                        .addComponent(field_employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_employeeAddress)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(lbl_personalData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(field_employeeRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_employeeUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_employeeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(lbl_employeePassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_employeeUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lbl_userData))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(field_employeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(btn_cancel)
                                .addGap(100, 100, 100)
                                .addComponent(btn_register)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tittle)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_personalData)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_employeeName))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_employeePhone)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_employePhoneLada)
                            .addComponent(field_employeePhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_employeePhoneNumber)
                            .addComponent(field_employeePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lbl_employeeAddress)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(field_employeeAddressColony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_employeeAddressPostalCode)
                                .addComponent(field_employeeAddressPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_employeeAddressColony))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lbl_employeeAddressStreet))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(field_employeeAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_employeeAddressCross)
                                        .addComponent(field_employeeAddressCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(field_employeeRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lbl_userData)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_employeeUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(field_employeeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_employeePassword)
                                .addComponent(field_employeeUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(field_employeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancel)
                            .addComponent(btn_register)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName("icono");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_employeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeNameActionPerformed

    private void field_employeePhoneLadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeePhoneLadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeePhoneLadaActionPerformed

    private void field_employeeAddressPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeAddressPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeAddressPostalCodeActionPerformed

    private void field_employeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeEmailActionPerformed

    private void field_employeeRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeRFCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegisterView().setVisible(true);
            }
        });
        
    }

    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JButton getBtn_register() {
        return btn_register;
    }

    public void setBtn_register(JButton btn_register) {
        this.btn_register = btn_register;
    }

    public JTextField getField_employeeAddressColony() {
        return field_employeeAddressColony;
    }

    public void setField_employeeAddressColony(JTextField field_employeeAddressColony) {
        this.field_employeeAddressColony = field_employeeAddressColony;
    }

    public JTextField getField_employeeAddressCross() {
        return field_employeeAddressCross;
    }

    public void setField_employeeAddressCross(JTextField field_employeeAddressCross) {
        this.field_employeeAddressCross = field_employeeAddressCross;
    }

    public JTextField getField_employeeAddressPostalCode() {
        return field_employeeAddressPostalCode;
    }

    public void setField_employeeAddressPostalCode(JTextField field_employeeAddressPostalCode) {
        this.field_employeeAddressPostalCode = field_employeeAddressPostalCode;
    }

    public JTextField getField_employeeAddressStreet() {
        return field_employeeAddressStreet;
    }

    public JTextField getField_employeeEmail() {
        return field_employeeEmail;
    }

    public JTextField getField_employeeRFC() {
        return field_employeeRFC;
    }

    public void setField_employeeRFC(JTextField field_employeeRFC) {
        this.field_employeeRFC = field_employeeRFC;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setField_employeeEmail(JTextField field_employeeEmail) {
        this.field_employeeEmail = field_employeeEmail;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setField_employeeAddressStreet(JTextField field_employeeAddressStreet) {
        this.field_employeeAddressStreet = field_employeeAddressStreet;
    }

    public JTextField getField_employeeName() {
        return field_employeeName;
    }

    public void setField_employeeName(JTextField field_employeeName) {
        this.field_employeeName = field_employeeName;
    }

    public JTextField getField_employeeUserPassword() {
        return field_employeeUserPassword;
    }

    public void setField_employeeUserPassword(JPasswordField field_employeePassword) {
        this.field_employeeUserPassword = field_employeePassword;
    }

    public JTextField getField_employeePhoneLada() {
        return field_employeePhoneLada;
    }

    public void setField_employeePhoneLada(JTextField field_employeePhoneLada) {
        this.field_employeePhoneLada = field_employeePhoneLada;
    }

    public JTextField getField_employeePhoneNumber() {
        return field_employeePhoneNumber;
    }

    public void setField_employeePhoneNumber(JTextField field_employeePhoneNumber) {
        this.field_employeePhoneNumber = field_employeePhoneNumber;
    }

    public JTextField getField_employeeUserName() {
        return field_employeeUserName;
    }

    public void setField_employeeUserName(JTextField field_employeeUserName) {
        this.field_employeeUserName = field_employeeUserName;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLbl_employePhoneLada() {
        return lbl_employePhoneLada;
    }

    public void setLbl_employePhoneLada(JLabel lbl_employePhoneLada) {
        this.lbl_employePhoneLada = lbl_employePhoneLada;
    }

    public JLabel getLbl_employeeAddress() {
        return lbl_employeeAddress;
    }

    public void setLbl_employeeAddress(JLabel lbl_employeeAddress) {
        this.lbl_employeeAddress = lbl_employeeAddress;
    }

    public JLabel getLbl_employeeAddressColony() {
        return lbl_employeeAddressColony;
    }

    public void setLbl_employeeAddressColony(JLabel lbl_employeeAddressColony) {
        this.lbl_employeeAddressColony = lbl_employeeAddressColony;
    }

    public JLabel getLbl_employeeAddressCross() {
        return lbl_employeeAddressCross;
    }

    public void setLbl_employeeAddressCross(JLabel lbl_employeeAddressCross) {
        this.lbl_employeeAddressCross = lbl_employeeAddressCross;
    }

    public JLabel getLbl_employeeAddressPostalCode() {
        return lbl_employeeAddressPostalCode;
    }

    public void setLbl_employeeAddressPostalCode(JLabel lbl_employeeAddressPostalCode) {
        this.lbl_employeeAddressPostalCode = lbl_employeeAddressPostalCode;
    }

    public JLabel getLbl_employeeAddressStreet() {
        return lbl_employeeAddressStreet;
    }

    public void setLbl_employeeAddressStreet(JLabel lbl_employeeAddressStreet) {
        this.lbl_employeeAddressStreet = lbl_employeeAddressStreet;
    }

    public JLabel getLbl_employeeName() {
        return lbl_employeeName;
    }

    public void setLbl_employeeName(JLabel lbl_employeeName) {
        this.lbl_employeeName = lbl_employeeName;
    }

    public JLabel getLbl_employeePassword() {
        return lbl_employeePassword;
    }

    public void setLbl_employeePassword(JLabel lbl_employeePassword) {
        this.lbl_employeePassword = lbl_employeePassword;
    }

    public JLabel getLbl_employeePhone() {
        return lbl_employeePhone;
    }

    public void setLbl_employeePhone(JLabel lbl_employeePhone) {
        this.lbl_employeePhone = lbl_employeePhone;
    }

    public JLabel getLbl_employeePhoneNumber() {
        return lbl_employeePhoneNumber;
    }

    public void setLbl_employeePhoneNumber(JLabel lbl_employeePhoneNumber) {
        this.lbl_employeePhoneNumber = lbl_employeePhoneNumber;
    }

    public JLabel getLbl_employeeUserName() {
        return lbl_employeeUserName;
    }

    public void setLbl_employeeUserName(JLabel lbl_employeeUserName) {
        this.lbl_employeeUserName = lbl_employeeUserName;
    }

    public JLabel getLbl_personalData() {
        return lbl_personalData;
    }

    public void setLbl_personalData(JLabel lbl_personalData) {
        this.lbl_personalData = lbl_personalData;
    }

    public JLabel getLbl_tittle() {
        return lbl_tittle;
    }

    public void setLbl_tittle(JLabel lbl_tittle) {
        this.lbl_tittle = lbl_tittle;
    }

    public JLabel getLbl_userData() {
        return lbl_userData;
    }

    public void setLbl_userData(JLabel lbl_userData) {
        this.lbl_userData = lbl_userData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField field_employeeAddressColony;
    private javax.swing.JTextField field_employeeAddressCross;
    private javax.swing.JTextField field_employeeAddressPostalCode;
    private javax.swing.JTextField field_employeeAddressStreet;
    private javax.swing.JTextField field_employeeEmail;
    private javax.swing.JTextField field_employeeName;
    private javax.swing.JTextField field_employeePhoneLada;
    private javax.swing.JTextField field_employeePhoneNumber;
    private javax.swing.JTextField field_employeeRFC;
    private javax.swing.JTextField field_employeeUserName;
    private javax.swing.JTextField field_employeeUserPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_employePhoneLada;
    private javax.swing.JLabel lbl_employeeAddress;
    private javax.swing.JLabel lbl_employeeAddressColony;
    private javax.swing.JLabel lbl_employeeAddressCross;
    private javax.swing.JLabel lbl_employeeAddressPostalCode;
    private javax.swing.JLabel lbl_employeeAddressStreet;
    private javax.swing.JLabel lbl_employeeName;
    private javax.swing.JLabel lbl_employeePassword;
    private javax.swing.JLabel lbl_employeePhone;
    private javax.swing.JLabel lbl_employeePhoneNumber;
    private javax.swing.JLabel lbl_employeeUserName;
    private javax.swing.JLabel lbl_personalData;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.JLabel lbl_userData;
    // End of variables declaration//GEN-END:variables
}