/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Jorge
 */
public class ProductSelectionView extends javax.swing.JFrame {

    /**
     * Creates new form productRegisterView
     */
    public ProductSelectionView() {
        initComponents();
        radioGroup_value();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup_value = new javax.swing.ButtonGroup();
        lbl_tittle = new javax.swing.JLabel();
        btn_continue = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_selection = new javax.swing.JLabel();
        radio_selectionMedicine = new javax.swing.JRadioButton();
        radio_selectionVaccine = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tittle.setText("Registro de Prodcutos");

        btn_continue.setText("Continuar");
        btn_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continueActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");

        lbl_selection.setText("¿Que tipo de Producto deseas registrar?");

        radio_selectionMedicine.setText("Medicamento");
        radio_selectionMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_selectionMedicineActionPerformed(evt);
            }
        });

        radio_selectionVaccine.setText("Vacuna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 404, Short.MAX_VALUE)
                .addComponent(lbl_tittle))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_continue)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lbl_selection))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(radio_selectionMedicine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio_selectionVaccine)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_tittle)
                .addGap(41, 41, 41)
                .addComponent(lbl_selection)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_selectionMedicine)
                    .addComponent(radio_selectionVaccine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_continue)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_continueActionPerformed

    private void radio_selectionMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_selectionMedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_selectionMedicineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSelectionView().setVisible(true);
            }
        });
        
        
    }
    
     public int getRadioGroupValue(){
        
        if(radio_selectionMedicine.isSelected()){
            return 1;
        }
        if(radio_selectionVaccine.isSelected()){
            return 2;
        }
        
        return 0;
    }
    
    private void radioGroup_value(){
        ButtonGroup bg1 = radioGroup_value;
        bg1.add(radio_selectionMedicine);
        bg1.add(radio_selectionVaccine);

    }

    public ButtonGroup getRadioGroup_value() {
        return radioGroup_value;
    }

    public void setRadioGroup_value(ButtonGroup radioGroup_value) {
        this.radioGroup_value = radioGroup_value;
    }

    
    
    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JButton getBtn_continue() {
        return btn_continue;
    }

    public void setBtn_continue(JButton btn_continue) {
        this.btn_continue = btn_continue;
    }

    public JLabel getLbl_selection() {
        return lbl_selection;
    }

    public void setLbl_selection(JLabel lbl_selection) {
        this.lbl_selection = lbl_selection;
    }

    public JLabel getLbl_tittle() {
        return lbl_tittle;
    }

    public void setLbl_tittle(JLabel lbl_tittle) {
        this.lbl_tittle = lbl_tittle;
    }

    public JRadioButton getRadio_selectionMedicine() {
        return radio_selectionMedicine;
    }

    public void setRadio_selectionMedicine(JRadioButton radio_selectionMedicine) {
        this.radio_selectionMedicine = radio_selectionMedicine;
    }

    public JRadioButton getRadio_selectionVaccine() {
        return radio_selectionVaccine;
    }

    public void setRadio_selectionVaccine(JRadioButton radio_selectionVaccine) {
        this.radio_selectionVaccine = radio_selectionVaccine;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_continue;
    private javax.swing.JLabel lbl_selection;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.ButtonGroup radioGroup_value;
    private javax.swing.JRadioButton radio_selectionMedicine;
    private javax.swing.JRadioButton radio_selectionVaccine;
    // End of variables declaration//GEN-END:variables
}
