/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Jorge
 */
public class SupplierRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form SupplierRegisterView
     */
    public SupplierRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tittle = new javax.swing.JLabel();
        lbl_supplierName = new javax.swing.JLabel();
        lbl_supplierPhone = new javax.swing.JLabel();
        lbl_supplierPhoneLada = new javax.swing.JLabel();
        lbl_supplierPhoneNumber = new javax.swing.JLabel();
        field_supplierPhoneLada = new javax.swing.JTextField();
        field_supplierPhoneNumber = new javax.swing.JTextField();
        field_supplierName = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tittle.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lbl_tittle.setText("Registro de Proveedores");

        lbl_supplierName.setText("Nombre de la Empresa:");

        lbl_supplierPhone.setText("Telefono");

        lbl_supplierPhoneLada.setText("Clave Lada:");

        lbl_supplierPhoneNumber.setText("Telefono:");

        field_supplierPhoneLada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_supplierPhoneLadaActionPerformed(evt);
            }
        });

        field_supplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_supplierNameActionPerformed(evt);
            }
        });

        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/Cancel.png"))); // NOI18N

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/Check.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/purchase1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_tittle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(btn_register))
                            .addComponent(btn_cancel)
                            .addComponent(lbl_supplierPhone)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbl_supplierName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field_supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_supplierPhoneLada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_supplierPhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_supplierPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_supplierPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_tittle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_supplierName)
                    .addComponent(field_supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lbl_supplierPhone)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_supplierPhoneLada)
                    .addComponent(lbl_supplierPhoneNumber)
                    .addComponent(field_supplierPhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_supplierPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_supplierPhoneLadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_supplierPhoneLadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_supplierPhoneLadaActionPerformed

    private void field_supplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_supplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_supplierNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierRegisterView().setVisible(true);
            }
        });
    }

    public JButton getBtn_register() {
        return btn_register;
    }

    public void setBtn_register(JButton btn_Register) {
        this.btn_register = btn_Register;
    }

    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JTextField getField_supplierName() {
        return field_supplierName;
    }

    public void setField_supplierName(JTextField field_supplierName) {
        this.field_supplierName = field_supplierName;
    }

    public JTextField getField_supplierPhoneLada() {
        return field_supplierPhoneLada;
    }

    public void setField_supplierPhoneLada(JTextField field_supplierPhoneLada) {
        this.field_supplierPhoneLada = field_supplierPhoneLada;
    }

    public JTextField getField_supplierPhoneNumber() {
        return field_supplierPhoneNumber;
    }

    public void setField_supplierPhoneNumber(JTextField field_supplierPhoneNumber) {
        this.field_supplierPhoneNumber = field_supplierPhoneNumber;
    }

    public JLabel getLbl_supplierName() {
        return lbl_supplierName;
    }

    public void setLbl_supplierName(JLabel lbl_supplierName) {
        this.lbl_supplierName = lbl_supplierName;
    }

    public JLabel getLbl_supplierPhone() {
        return lbl_supplierPhone;
    }

    public void setLbl_supplierPhone(JLabel lbl_supplierPhone) {
        this.lbl_supplierPhone = lbl_supplierPhone;
    }

    public JLabel getLbl_supplierPhoneLada() {
        return lbl_supplierPhoneLada;
    }

    public void setLbl_supplierPhoneLada(JLabel lbl_supplierPhoneLada) {
        this.lbl_supplierPhoneLada = lbl_supplierPhoneLada;
    }

    public JLabel getLbl_supplierPhoneNumber() {
        return lbl_supplierPhoneNumber;
    }

    public void setLbl_supplierPhoneNumber(JLabel lbl_supplierPhoneNumber) {
        this.lbl_supplierPhoneNumber = lbl_supplierPhoneNumber;
    }

    public JLabel getLbl_tittle() {
        return lbl_tittle;
    }

    public void setLbl_tittle(JLabel lbl_tittle) {
        this.lbl_tittle = lbl_tittle;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField field_supplierName;
    private javax.swing.JTextField field_supplierPhoneLada;
    private javax.swing.JTextField field_supplierPhoneNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_supplierName;
    private javax.swing.JLabel lbl_supplierPhone;
    private javax.swing.JLabel lbl_supplierPhoneLada;
    private javax.swing.JLabel lbl_supplierPhoneNumber;
    private javax.swing.JLabel lbl_tittle;
    // End of variables declaration//GEN-END:variables
}