/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Jorge
 */
public class UserDoctorRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form UserDoctorRegisterController
     */
    public UserDoctorRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_userData = new javax.swing.JLabel();
        field_doctorUserName = new javax.swing.JTextField();
        field_doctorUserPassword = new javax.swing.JTextField();
        lbl_doctorUserName = new javax.swing.JLabel();
        lbl_doctorPassword = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_doctorUserEmail = new javax.swing.JLabel();
        field_doctorUserEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_userData.setText("Datos de usuario");

        lbl_doctorUserName.setText("Nombre de Usuario:");

        lbl_doctorPassword.setText("Contraseña:");

        btn_register.setText("Registrar");

        btn_cancel.setText("Cancelar");

        lbl_doctorUserEmail.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_userData)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(btn_register)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_doctorUserName)
                    .addComponent(lbl_doctorPassword)
                    .addComponent(lbl_doctorUserEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_doctorUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(field_doctorUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(field_doctorUserEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_userData)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorUserName)
                    .addComponent(field_doctorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorPassword)
                    .addComponent(field_doctorUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorUserEmail)
                    .addComponent(field_doctorUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_register))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDoctorRegisterView().setVisible(true);
            }
        });
    }

    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JButton getBtn_register() {
        return btn_register;
    }

    public void setBtn_register(JButton btn_register) {
        this.btn_register = btn_register;
    }

    public JTextField getField_doctorUserEmail() {
        return field_doctorUserEmail;
    }

    public void setField_doctorUserEmail(JTextField field_doctorUserEmail) {
        this.field_doctorUserEmail = field_doctorUserEmail;
    }

    public JTextField getField_doctorUserName() {
        return field_doctorUserName;
    }

    public void setField_doctorUserName(JTextField field_doctorUserName) {
        this.field_doctorUserName = field_doctorUserName;
    }

    public JTextField getField_doctorUserPassword() {
        return field_doctorUserPassword;
    }

    public void setField_doctorUserPassword(JTextField field_doctorUserPassword) {
        this.field_doctorUserPassword = field_doctorUserPassword;
    }

    public JLabel getLbl_doctorPassword() {
        return lbl_doctorPassword;
    }

    public void setLbl_doctorPassword(JLabel lbl_doctorPassword) {
        this.lbl_doctorPassword = lbl_doctorPassword;
    }

    public JLabel getLbl_doctorUserEmail() {
        return lbl_doctorUserEmail;
    }

    public void setLbl_doctorUserEmail(JLabel lbl_doctorUserEmail) {
        this.lbl_doctorUserEmail = lbl_doctorUserEmail;
    }

    public JLabel getLbl_doctorUserName() {
        return lbl_doctorUserName;
    }

    public void setLbl_doctorUserName(JLabel lbl_doctorUserName) {
        this.lbl_doctorUserName = lbl_doctorUserName;
    }

    public JLabel getLbl_userData() {
        return lbl_userData;
    }

    public void setLbl_userData(JLabel lbl_userData) {
        this.lbl_userData = lbl_userData;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField field_doctorUserEmail;
    private javax.swing.JTextField field_doctorUserName;
    private javax.swing.JTextField field_doctorUserPassword;
    private javax.swing.JLabel lbl_doctorPassword;
    private javax.swing.JLabel lbl_doctorUserEmail;
    private javax.swing.JLabel lbl_doctorUserName;
    private javax.swing.JLabel lbl_userData;
    // End of variables declaration//GEN-END:variables
}