/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

/**
 *
 * @author Jorge
 */
public class DoctorRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form DoctorRegisterView
     */
    public DoctorRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tittle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        field_doctorAddressPostalCode = new javax.swing.JTextField();
        field_doctorAddressCross = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_doctorName = new javax.swing.JLabel();
        lbl_doctorPhone = new javax.swing.JLabel();
        lbl_doctorAddress = new javax.swing.JLabel();
        lbl_userData = new javax.swing.JLabel();
        lbl_doctorUserName = new javax.swing.JLabel();
        lbl_doctorPassword = new javax.swing.JLabel();
        field_employeeName = new javax.swing.JTextField();
        field_doctorPassword = new javax.swing.JPasswordField();
        field_doctorUserName = new javax.swing.JTextField();
        lbl_personalData = new javax.swing.JLabel();
        lbl_doctorPhoneLada = new javax.swing.JLabel();
        field_doctorPhoneLada = new javax.swing.JTextField();
        lbl_doctorPhoneNumber = new javax.swing.JLabel();
        field_doctorPhoneNumber = new javax.swing.JTextField();
        lbl_doctorAddressStreet = new javax.swing.JLabel();
        lbl_doctorAddressColony = new javax.swing.JLabel();
        lbl_doctorAddressPostalCode = new javax.swing.JLabel();
        lbl_doctorAddressCross = new javax.swing.JLabel();
        field_doctorAddressStreet = new javax.swing.JTextField();
        field_doctorAddressColony = new javax.swing.JTextField();
        lbl_doctorEmail = new javax.swing.JLabel();
        field_doctorEmail = new javax.swing.JTextField();
        lbl_doctorRFC = new javax.swing.JLabel();
        lbl_doctorProfessionalCode = new javax.swing.JLabel();
        field_doctorRFC = new javax.swing.JTextField();
        field_doctorProfessionalCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tittle.setText("Registro de Doctor");

        jButton1.setText("Registrar");

        jButton2.setText("Cancelar");

        field_doctorAddressPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_doctorAddressPostalCodeActionPerformed(evt);
            }
        });

        lbl_doctorName.setText("Nombre:");

        lbl_doctorPhone.setText("Telefono");

        lbl_doctorAddress.setText("Direccion");

        lbl_userData.setText("Datos de usuario");

        lbl_doctorUserName.setText("Nombre de Usuario:");

        lbl_doctorPassword.setText("Contraseña:");

        field_employeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeNameActionPerformed(evt);
            }
        });

        field_doctorPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_doctorPasswordActionPerformed(evt);
            }
        });

        lbl_personalData.setText("Datos personales");

        lbl_doctorPhoneLada.setText("Clave lada:");

        field_doctorPhoneLada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_doctorPhoneLadaActionPerformed(evt);
            }
        });

        lbl_doctorPhoneNumber.setText("digitos:");

        lbl_doctorAddressStreet.setText("calle:");

        lbl_doctorAddressColony.setText("colonia:");

        lbl_doctorAddressPostalCode.setText("numeroPostal:");

        lbl_doctorAddressCross.setText("cruzamientos:");

        lbl_doctorEmail.setText("Correo Electronico:");

        lbl_doctorRFC.setText("RFC:");

        lbl_doctorProfessionalCode.setText("Cedula Profesional:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_tittle)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_userData)
                        .addGap(329, 329, 329))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lbl_doctorPhoneNumber)
                                .addGap(18, 18, 18)
                                .addComponent(field_doctorPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(lbl_doctorPhoneLada)
                                .addGap(49, 49, 49)
                                .addComponent(field_doctorPhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_doctorAddressStreet)
                                            .addComponent(lbl_doctorAddress))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(field_doctorAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(lbl_doctorAddressColony)
                                        .addGap(18, 18, 18)
                                        .addComponent(field_doctorAddressColony, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_doctorAddressPostalCode)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(field_doctorAddressPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(lbl_doctorAddressCross)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(field_doctorAddressCross, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_doctorEmail)
                                            .addComponent(lbl_doctorRFC)
                                            .addComponent(lbl_doctorProfessionalCode))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(field_doctorEmail)
                                            .addComponent(field_doctorRFC)
                                            .addComponent(field_doctorProfessionalCode, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_doctorPassword)
                            .addComponent(lbl_doctorUserName))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(field_doctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_doctorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_personalData)
                .addGap(326, 326, 326))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_doctorPhone)
                        .addComponent(lbl_doctorName))
                    .addGap(54, 54, 54)
                    .addComponent(field_employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_tittle)
                .addGap(13, 13, 13)
                .addComponent(lbl_personalData)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorPhoneNumber)
                    .addComponent(field_doctorPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_doctorPhoneLada)
                    .addComponent(field_doctorPhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lbl_doctorAddress)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorAddressStreet)
                    .addComponent(field_doctorAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_doctorAddressColony)
                    .addComponent(field_doctorAddressColony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_doctorAddressPostalCode)
                    .addComponent(field_doctorAddressPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_doctorAddressCross)
                    .addComponent(field_doctorAddressCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorEmail)
                    .addComponent(field_doctorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorRFC)
                    .addComponent(field_doctorRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorProfessionalCode)
                    .addComponent(field_doctorProfessionalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_userData)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_doctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_doctorUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doctorPassword)
                    .addComponent(field_doctorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(field_employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_doctorName))
                    .addGap(41, 41, 41)
                    .addComponent(lbl_doctorPhone)
                    .addContainerGap(470, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_doctorAddressPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_doctorAddressPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_doctorAddressPostalCodeActionPerformed

    private void field_employeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeNameActionPerformed

    private void field_doctorPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_doctorPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_doctorPasswordActionPerformed

    private void field_doctorPhoneLadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_doctorPhoneLadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_doctorPhoneLadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_doctorAddressColony;
    private javax.swing.JTextField field_doctorAddressCross;
    private javax.swing.JTextField field_doctorAddressPostalCode;
    private javax.swing.JTextField field_doctorAddressStreet;
    private javax.swing.JTextField field_doctorEmail;
    private javax.swing.JPasswordField field_doctorPassword;
    private javax.swing.JTextField field_doctorPhoneLada;
    private javax.swing.JTextField field_doctorPhoneNumber;
    private javax.swing.JTextField field_doctorProfessionalCode;
    private javax.swing.JTextField field_doctorRFC;
    private javax.swing.JTextField field_doctorUserName;
    private javax.swing.JTextField field_employeeName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_doctorAddress;
    private javax.swing.JLabel lbl_doctorAddressColony;
    private javax.swing.JLabel lbl_doctorAddressCross;
    private javax.swing.JLabel lbl_doctorAddressPostalCode;
    private javax.swing.JLabel lbl_doctorAddressStreet;
    private javax.swing.JLabel lbl_doctorEmail;
    private javax.swing.JLabel lbl_doctorName;
    private javax.swing.JLabel lbl_doctorPassword;
    private javax.swing.JLabel lbl_doctorPhone;
    private javax.swing.JLabel lbl_doctorPhoneLada;
    private javax.swing.JLabel lbl_doctorPhoneNumber;
    private javax.swing.JLabel lbl_doctorProfessionalCode;
    private javax.swing.JLabel lbl_doctorRFC;
    private javax.swing.JLabel lbl_doctorUserName;
    private javax.swing.JLabel lbl_personalData;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.JLabel lbl_userData;
    // End of variables declaration//GEN-END:variables
}
