/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Jorge
 */
public class EmployeeRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form registerView
     */
    public EmployeeRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tittle = new javax.swing.JLabel();
        lbl_employeeName = new javax.swing.JLabel();
        lbl_employeePhone = new javax.swing.JLabel();
        lbl_employeeAddress = new javax.swing.JLabel();
        lbl_userData = new javax.swing.JLabel();
        lbl_employeeUserName = new javax.swing.JLabel();
        lbl_employeePassword = new javax.swing.JLabel();
        field_employeeName = new javax.swing.JTextField();
        field_employeePassword = new javax.swing.JPasswordField();
        field_employeeUserName = new javax.swing.JTextField();
        lbl_personalData = new javax.swing.JLabel();
        lbl_employePhoneLada = new javax.swing.JLabel();
        field_employeePhoneLada = new javax.swing.JTextField();
        lbl_employeePhoneNumber = new javax.swing.JLabel();
        field_employeePhoneNumber = new javax.swing.JTextField();
        lbl_employeeAddressStreet = new javax.swing.JLabel();
        lbl_employeeAddressColony = new javax.swing.JLabel();
        lbl_employeeAddressPostalCode = new javax.swing.JLabel();
        lbl_employeeAddressCross = new javax.swing.JLabel();
        field_employeeAddressStreet = new javax.swing.JTextField();
        field_employeeAddressColony = new javax.swing.JTextField();
        field_employeeAddressPostalCode = new javax.swing.JTextField();
        field_employeeAddressCross = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tittle.setText("Registro de Empleado");

        lbl_employeeName.setText("Nombre:");

        lbl_employeePhone.setText("Telefono");

        lbl_employeeAddress.setText("Direccion");

        lbl_userData.setText("Datos de usuario");

        lbl_employeeUserName.setText("Nombre de Usuario:");

        lbl_employeePassword.setText("Contraseña:");

        field_employeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeNameActionPerformed(evt);
            }
        });

        field_employeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeePasswordActionPerformed(evt);
            }
        });

        lbl_personalData.setText("Datos personales");

        lbl_employePhoneLada.setText("Clave lada:");

        field_employeePhoneLada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeePhoneLadaActionPerformed(evt);
            }
        });

        lbl_employeePhoneNumber.setText("digitos:");

        lbl_employeeAddressStreet.setText("calle:");

        lbl_employeeAddressColony.setText("colonia:");

        lbl_employeeAddressPostalCode.setText("numeroPostal:");

        lbl_employeeAddressCross.setText("cruzamientos:");

        field_employeeAddressPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_employeeAddressPostalCodeActionPerformed(evt);
            }
        });

        btn_register.setText("Registrar");

        btn_cancel.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_employeeUserName)
                                    .addComponent(lbl_employeePassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_employeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field_employeeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lbl_employeePhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(field_employeePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_employeeAddress)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_employeePhone)
                                        .addComponent(lbl_employeeName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_employeeAddressStreet)
                                        .addGap(18, 18, 18)
                                        .addComponent(field_employeeAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(171, 171, 171)
                                                .addComponent(lbl_employePhoneLada)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(field_employeePhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(lbl_employeeAddressColony)
                                                .addGap(18, 18, 18)
                                                .addComponent(field_employeeAddressColony, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_employeeAddressPostalCode)))
                                        .addGap(18, 18, 18)
                                        .addComponent(field_employeeAddressPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(lbl_employeeAddressCross)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(field_employeeAddressCross, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_tittle))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_register)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_userData)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_personalData)
                        .addGap(321, 321, 321))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_tittle)
                .addGap(31, 31, 31)
                .addComponent(lbl_personalData)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_employeeName))
                .addGap(41, 41, 41)
                .addComponent(lbl_employeePhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_employePhoneLada)
                    .addComponent(field_employeePhoneLada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_employeePhoneNumber)
                    .addComponent(field_employeePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lbl_employeeAddress)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_employeeAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_employeeAddressColony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_employeeAddressPostalCode)
                            .addComponent(field_employeeAddressPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_employeeAddressCross)
                            .addComponent(field_employeeAddressCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_employeeAddressStreet)
                            .addComponent(lbl_employeeAddressColony))
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_userData)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_employeeUserName))
                    .addComponent(field_employeeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_employeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_employeePassword))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_employeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeNameActionPerformed

    private void field_employeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeePasswordActionPerformed

    private void field_employeePhoneLadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeePhoneLadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeePhoneLadaActionPerformed

    private void field_employeeAddressPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_employeeAddressPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_employeeAddressPostalCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegisterView().setVisible(true);
            }
        });
        
    }

    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JButton getBtn_register() {
        return btn_register;
    }

    public void setBtn_register(JButton btn_register) {
        this.btn_register = btn_register;
    }

    public JTextField getField_employeeAddressColony() {
        return field_employeeAddressColony;
    }

    public void setField_employeeAddressColony(JTextField field_employeeAddressColony) {
        this.field_employeeAddressColony = field_employeeAddressColony;
    }

    public JTextField getField_employeeAddressCross() {
        return field_employeeAddressCross;
    }

    public void setField_employeeAddressCross(JTextField field_employeeAddressCross) {
        this.field_employeeAddressCross = field_employeeAddressCross;
    }

    public JTextField getField_employeeAddressPostalCode() {
        return field_employeeAddressPostalCode;
    }

    public void setField_employeeAddressPostalCode(JTextField field_employeeAddressPostalCode) {
        this.field_employeeAddressPostalCode = field_employeeAddressPostalCode;
    }

    public JTextField getField_employeeAddressStreet() {
        return field_employeeAddressStreet;
    }

    public void setField_employeeAddressStreet(JTextField field_employeeAddressStreet) {
        this.field_employeeAddressStreet = field_employeeAddressStreet;
    }

    public JTextField getField_employeeName() {
        return field_employeeName;
    }

    public void setField_employeeName(JTextField field_employeeName) {
        this.field_employeeName = field_employeeName;
    }

    public JPasswordField getField_employeePassword() {
        return field_employeePassword;
    }

    public void setField_employeePassword(JPasswordField field_employeePassword) {
        this.field_employeePassword = field_employeePassword;
    }

    public JTextField getField_employeePhoneLada() {
        return field_employeePhoneLada;
    }

    public void setField_employeePhoneLada(JTextField field_employeePhoneLada) {
        this.field_employeePhoneLada = field_employeePhoneLada;
    }

    public JTextField getField_employeePhoneNumber() {
        return field_employeePhoneNumber;
    }

    public void setField_employeePhoneNumber(JTextField field_employeePhoneNumber) {
        this.field_employeePhoneNumber = field_employeePhoneNumber;
    }

    public JTextField getField_employeeUserName() {
        return field_employeeUserName;
    }

    public void setField_employeeUserName(JTextField field_employeeUserName) {
        this.field_employeeUserName = field_employeeUserName;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLbl_employePhoneLada() {
        return lbl_employePhoneLada;
    }

    public void setLbl_employePhoneLada(JLabel lbl_employePhoneLada) {
        this.lbl_employePhoneLada = lbl_employePhoneLada;
    }

    public JLabel getLbl_employeeAddress() {
        return lbl_employeeAddress;
    }

    public void setLbl_employeeAddress(JLabel lbl_employeeAddress) {
        this.lbl_employeeAddress = lbl_employeeAddress;
    }

    public JLabel getLbl_employeeAddressColony() {
        return lbl_employeeAddressColony;
    }

    public void setLbl_employeeAddressColony(JLabel lbl_employeeAddressColony) {
        this.lbl_employeeAddressColony = lbl_employeeAddressColony;
    }

    public JLabel getLbl_employeeAddressCross() {
        return lbl_employeeAddressCross;
    }

    public void setLbl_employeeAddressCross(JLabel lbl_employeeAddressCross) {
        this.lbl_employeeAddressCross = lbl_employeeAddressCross;
    }

    public JLabel getLbl_employeeAddressPostalCode() {
        return lbl_employeeAddressPostalCode;
    }

    public void setLbl_employeeAddressPostalCode(JLabel lbl_employeeAddressPostalCode) {
        this.lbl_employeeAddressPostalCode = lbl_employeeAddressPostalCode;
    }

    public JLabel getLbl_employeeAddressStreet() {
        return lbl_employeeAddressStreet;
    }

    public void setLbl_employeeAddressStreet(JLabel lbl_employeeAddressStreet) {
        this.lbl_employeeAddressStreet = lbl_employeeAddressStreet;
    }

    public JLabel getLbl_employeeName() {
        return lbl_employeeName;
    }

    public void setLbl_employeeName(JLabel lbl_employeeName) {
        this.lbl_employeeName = lbl_employeeName;
    }

    public JLabel getLbl_employeePassword() {
        return lbl_employeePassword;
    }

    public void setLbl_employeePassword(JLabel lbl_employeePassword) {
        this.lbl_employeePassword = lbl_employeePassword;
    }

    public JLabel getLbl_employeePhone() {
        return lbl_employeePhone;
    }

    public void setLbl_employeePhone(JLabel lbl_employeePhone) {
        this.lbl_employeePhone = lbl_employeePhone;
    }

    public JLabel getLbl_employeePhoneNumber() {
        return lbl_employeePhoneNumber;
    }

    public void setLbl_employeePhoneNumber(JLabel lbl_employeePhoneNumber) {
        this.lbl_employeePhoneNumber = lbl_employeePhoneNumber;
    }

    public JLabel getLbl_employeeUserName() {
        return lbl_employeeUserName;
    }

    public void setLbl_employeeUserName(JLabel lbl_employeeUserName) {
        this.lbl_employeeUserName = lbl_employeeUserName;
    }

    public JLabel getLbl_personalData() {
        return lbl_personalData;
    }

    public void setLbl_personalData(JLabel lbl_personalData) {
        this.lbl_personalData = lbl_personalData;
    }

    public JLabel getLbl_tittle() {
        return lbl_tittle;
    }

    public void setLbl_tittle(JLabel lbl_tittle) {
        this.lbl_tittle = lbl_tittle;
    }

    public JLabel getLbl_userData() {
        return lbl_userData;
    }

    public void setLbl_userData(JLabel lbl_userData) {
        this.lbl_userData = lbl_userData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField field_employeeAddressColony;
    private javax.swing.JTextField field_employeeAddressCross;
    private javax.swing.JTextField field_employeeAddressPostalCode;
    private javax.swing.JTextField field_employeeAddressStreet;
    private javax.swing.JTextField field_employeeName;
    private javax.swing.JPasswordField field_employeePassword;
    private javax.swing.JTextField field_employeePhoneLada;
    private javax.swing.JTextField field_employeePhoneNumber;
    private javax.swing.JTextField field_employeeUserName;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_employePhoneLada;
    private javax.swing.JLabel lbl_employeeAddress;
    private javax.swing.JLabel lbl_employeeAddressColony;
    private javax.swing.JLabel lbl_employeeAddressCross;
    private javax.swing.JLabel lbl_employeeAddressPostalCode;
    private javax.swing.JLabel lbl_employeeAddressStreet;
    private javax.swing.JLabel lbl_employeeName;
    private javax.swing.JLabel lbl_employeePassword;
    private javax.swing.JLabel lbl_employeePhone;
    private javax.swing.JLabel lbl_employeePhoneNumber;
    private javax.swing.JLabel lbl_employeeUserName;
    private javax.swing.JLabel lbl_personalData;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.JLabel lbl_userData;
    // End of variables declaration//GEN-END:variables
}
