/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Jorge
 */
public class MedicineRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form productRegisterView
     */
    public MedicineRegisterView() {
        initComponents();
        loadComboAdministrationWay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tittle = new javax.swing.JLabel();
        lbl_productName = new javax.swing.JLabel();
        lbl_productQuantity = new javax.swing.JLabel();
        lbl_productSellPrize = new javax.swing.JLabel();
        field_productName = new javax.swing.JTextField();
        field_productQuantity = new javax.swing.JTextField();
        field_productSellPrize = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_productExpirationDate = new javax.swing.JLabel();
        lbl_productDose = new javax.swing.JLabel();
        spinner_productDoseQuantity = new javax.swing.JSpinner();
        combo_productDoseQuantityType = new javax.swing.JComboBox<String>();
        spinner_productDosePeriod = new javax.swing.JSpinner();
        combo_dosePeriodType = new javax.swing.JComboBox<String>();
        lbl_productDoseQuantity = new javax.swing.JLabel();
        lbl_productDosePeriod = new javax.swing.JLabel();
        lbl_productAdmnistrationWay = new javax.swing.JLabel();
        combo_productAdministrationWay = new javax.swing.JComboBox<String>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tittle.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lbl_tittle.setText("Registro de Medicamentos");

        lbl_productName.setText("Nombre:");

        lbl_productQuantity.setText("Cantidad:");

        lbl_productSellPrize.setText("Precio de Venta:");

        field_productQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_productQuantityActionPerformed(evt);
            }
        });

        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/Check.png"))); // NOI18N
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/Cancel.png"))); // NOI18N

        lbl_productExpirationDate.setText("Fecha Caducidad:");

        lbl_productDose.setText("Dosis:");

        combo_productDoseQuantityType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pastillas", "Gotas" }));
        combo_productDoseQuantityType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_productDoseQuantityTypeActionPerformed(evt);
            }
        });

        combo_dosePeriodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Minutos", "Horas", "Dias" }));

        lbl_productDoseQuantity.setText("Cantidad:");

        lbl_productDosePeriod.setText("Tiempo:");

        lbl_productAdmnistrationWay.setText("Administracion:");

        combo_productAdministrationWay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dateChooser.setDateFormatString("yyyy-MM-dd");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Module1/icons-large/medicines.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_productDoseQuantity)
                            .addGap(18, 18, 18)
                            .addComponent(spinner_productDoseQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(combo_productDoseQuantityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl_productDosePeriod)
                                    .addGap(18, 18, 18)
                                    .addComponent(spinner_productDosePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_cancel)
                                    .addGap(48, 48, 48)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_register)
                                .addComponent(combo_dosePeriodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_productSellPrize)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_productName))
                            .addComponent(lbl_productQuantity))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_productSellPrize, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_productDose)
                    .addComponent(lbl_productExpirationDate)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_productAdmnistrationWay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_productAdministrationWay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_tittle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tittle)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_productName)
                            .addComponent(field_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_productAdmnistrationWay)
                            .addComponent(combo_productAdministrationWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_productQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_productSellPrize)
                            .addComponent(field_productSellPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(lbl_productExpirationDate)
                        .addGap(18, 18, 18)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_productDose)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_productDoseQuantity)
                            .addComponent(spinner_productDoseQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_productDoseQuantityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_productDosePeriod)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spinner_productDosePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_dosePeriodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cancel)
                            .addComponent(btn_register))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registerActionPerformed

    private void combo_productDoseQuantityTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_productDoseQuantityTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_productDoseQuantityTypeActionPerformed

    private void field_productQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_productQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_productQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineRegisterView().setVisible(true);
            }
        });

    }
    
    public void loadComboAdministrationWay(){
        this.getCombo_productAdministrationWay().removeAllItems();
        this.getCombo_productAdministrationWay().addItem("Oral");
        this.getCombo_productAdministrationWay().addItem("Rectal");
        this.getCombo_productAdministrationWay().addItem("Intravenosa");
    }
    
    public JButton getBtn_register() {
        return btn_register;
    }

    public void setBtn_register(JButton btn_register) {
        this.btn_register = btn_register;
    }

    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JComboBox<String> getCombo_dosePeriodType() {
        return combo_dosePeriodType;
    }

    public void setCombo_dosePeriodType(JComboBox<String> combo_dosePeriodType) {
        this.combo_dosePeriodType = combo_dosePeriodType;
    }

    public JComboBox<String> getCombo_productAdministrationWay() {
        return combo_productAdministrationWay;
    }

    public void setCombo_productAdministrationWay(JComboBox<String> combo_productAdministrationWay) {
        this.combo_productAdministrationWay = combo_productAdministrationWay;
    }

    public JComboBox<String> getCombo_productDoseQuantityType() {
        return combo_productDoseQuantityType;
    }

    public void setCombo_productDoseQuantityType(JComboBox<String> combo_productDoseQuantityType) {
        this.combo_productDoseQuantityType = combo_productDoseQuantityType;
    }

    public JTextField getField_productName() {
        return field_productName;
    }

    public void setField_productName(JTextField field_productName) {
        this.field_productName = field_productName;
    }

    public JTextField getField_productQuantity() {
        return field_productQuantity;
    }

    public void setField_productQuantity(JTextField field_productQuantity) {
        this.field_productQuantity = field_productQuantity;
    }

    public JTextField getField_productSellPrize() {
        return field_productSellPrize;
    }

    public void setField_productSellPrize(JTextField field_productSellPrize) {
        this.field_productSellPrize = field_productSellPrize;
    }

    public JLabel getLbl_productAdmnistrationWay() {
        return lbl_productAdmnistrationWay;
    }

    public void setLbl_productAdmnistrationWay(JLabel lbl_productAdmnistrationWay) {
        this.lbl_productAdmnistrationWay = lbl_productAdmnistrationWay;
    }

    public JLabel getLbl_productDose() {
        return lbl_productDose;
    }

    public void setLbl_productDose(JLabel lbl_productDose) {
        this.lbl_productDose = lbl_productDose;
    }

    public JLabel getLbl_productDosePeriod() {
        return lbl_productDosePeriod;
    }

    public void setLbl_productDosePeriod(JLabel lbl_productDosePeriod) {
        this.lbl_productDosePeriod = lbl_productDosePeriod;
    }

    public JLabel getLbl_productDoseQuantity() {
        return lbl_productDoseQuantity;
    }

    public void setLbl_productDoseQuantity(JLabel lbl_productDoseQuantity) {
        this.lbl_productDoseQuantity = lbl_productDoseQuantity;
    }

    public JLabel getLbl_productExpirationDate() {
        return lbl_productExpirationDate;
    }

    public void setLbl_productExpirationDate(JLabel lbl_productExpirationDate) {
        this.lbl_productExpirationDate = lbl_productExpirationDate;
    }

    public JLabel getLbl_productName() {
        return lbl_productName;
    }

    public void setLbl_productName(JLabel lbl_productName) {
        this.lbl_productName = lbl_productName;
    }

    public JLabel getLbl_productQuantity() {
        return lbl_productQuantity;
    }

    public void setLbl_productQuantity(JLabel lbl_productQuantity) {
        this.lbl_productQuantity = lbl_productQuantity;
    }

    public JLabel getLbl_productSellPrize() {
        return lbl_productSellPrize;
    }

    public void setLbl_productSellPrize(JLabel lbl_productSellPrize) {
        this.lbl_productSellPrize = lbl_productSellPrize;
    }

    public JLabel getLbl_tittle() {
        return lbl_tittle;
    }

    public void setLbl_tittle(JLabel lbl_tittle) {
        this.lbl_tittle = lbl_tittle;
    }

    public JSpinner getSpinner_productDosePeriod() {
        return spinner_productDosePeriod;
    }

    public void setSpinner_productDosePeriod(JSpinner spinner_productDosePeriod) {
        this.spinner_productDosePeriod = spinner_productDosePeriod;
    }

    public JSpinner getSpinner_productDoseQuantity() {
        return spinner_productDoseQuantity;
    }

    public void setSpinner_productDoseQuantity(JSpinner spinner_productDoseQuantity) {
        this.spinner_productDoseQuantity = spinner_productDoseQuantity;
    }

    public JDateChooser getDateChooser() {
        return dateChooser;
    }

    public void setDateChooser(JDateChooser dateChooser) {
        this.dateChooser = dateChooser;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JComboBox<String> combo_dosePeriodType;
    private javax.swing.JComboBox<String> combo_productAdministrationWay;
    private javax.swing.JComboBox<String> combo_productDoseQuantityType;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextField field_productName;
    private javax.swing.JTextField field_productQuantity;
    private javax.swing.JTextField field_productSellPrize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_productAdmnistrationWay;
    private javax.swing.JLabel lbl_productDose;
    private javax.swing.JLabel lbl_productDosePeriod;
    private javax.swing.JLabel lbl_productDoseQuantity;
    private javax.swing.JLabel lbl_productExpirationDate;
    private javax.swing.JLabel lbl_productName;
    private javax.swing.JLabel lbl_productQuantity;
    private javax.swing.JLabel lbl_productSellPrize;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.JSpinner spinner_productDosePeriod;
    private javax.swing.JSpinner spinner_productDoseQuantity;
    // End of variables declaration//GEN-END:variables
}
