/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

/**
 *
 * @author Jorge
 */
public class MedicineRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form productRegisterView
     */
    public MedicineRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tittle = new javax.swing.JLabel();
        lbl_productName = new javax.swing.JLabel();
        lbl_productQuantity = new javax.swing.JLabel();
        lbl_productSellPrize = new javax.swing.JLabel();
        lbl_productSupplier = new javax.swing.JLabel();
        field_productName = new javax.swing.JTextField();
        field_productQuantity = new javax.swing.JTextField();
        field_productSellPrize = new javax.swing.JTextField();
        lbl_productCode = new javax.swing.JLabel();
        btn_Register = new javax.swing.JButton();
        field_productCode = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        combo_productSupplier = new javax.swing.JComboBox<>();
        lbl_productExpirationDate = new javax.swing.JLabel();
        spinner_productExpirationDay = new javax.swing.JSpinner();
        spinner_productExpirationMonth = new javax.swing.JSpinner();
        spinner_productExpirationYear = new javax.swing.JSpinner();
        lbl_productExpirationDay = new javax.swing.JLabel();
        lbl_productExpirationMonth = new javax.swing.JLabel();
        lbl_productExpirationYear = new javax.swing.JLabel();
        lbl_productDose = new javax.swing.JLabel();
        spinner_productDoseQuantity = new javax.swing.JSpinner();
        combo_productDoseQuantityType = new javax.swing.JComboBox<>();
        spinner_productDosePeriod = new javax.swing.JSpinner();
        combo_dosePeriodType = new javax.swing.JComboBox<>();
        lbl_productDoseQuantity = new javax.swing.JLabel();
        lbl_productDosePeriod = new javax.swing.JLabel();
        lbl_productAdmnistrationWay = new javax.swing.JLabel();
        combo_productAdministrationWay = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tittle.setText("Registro de Medicamentos");

        lbl_productName.setText("Nombre:");

        lbl_productQuantity.setText("Cantidad:");

        lbl_productSellPrize.setText("Precio de Venta:");

        lbl_productSupplier.setText("Proveedor:");

        field_productQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_productQuantityActionPerformed(evt);
            }
        });

        lbl_productCode.setText("Clave:");

        btn_Register.setText("Registrar");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");

        combo_productSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_productSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_productSupplierActionPerformed(evt);
            }
        });

        lbl_productExpirationDate.setText("Fecha Caducidad:");

        lbl_productExpirationDay.setText("Dia");

        lbl_productExpirationMonth.setText("Mes");

        lbl_productExpirationYear.setText("Año");

        lbl_productDose.setText("Dosis:");

        combo_productDoseQuantityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_productDoseQuantityType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_productDoseQuantityTypeActionPerformed(evt);
            }
        });

        combo_dosePeriodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_productDoseQuantity.setText("Cantidad:");

        lbl_productDosePeriod.setText("Tiempo:");

        lbl_productAdmnistrationWay.setText("Administracion:");

        combo_productAdministrationWay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Register)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_productSellPrize)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_productName)
                                .addComponent(lbl_productQuantity)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_productCode)
                                    .addComponent(field_productSellPrize, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(field_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(field_productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_productExpirationDay)
                                        .addGap(30, 30, 30)
                                        .addComponent(spinner_productExpirationDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_productExpirationMonth))
                                    .addComponent(field_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 31, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_tittle, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl_productExpirationYear)
                                                    .addComponent(lbl_productAdmnistrationWay)
                                                    .addComponent(lbl_productSupplier, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(30, 30, 30)
                                                        .addComponent(spinner_productExpirationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(combo_productSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(combo_productAdministrationWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(58, 58, 58))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinner_productExpirationMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_productDose)
                            .addComponent(lbl_productExpirationDate))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_productDoseQuantity)
                .addGap(18, 18, 18)
                .addComponent(spinner_productDoseQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_productDoseQuantityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lbl_productDosePeriod)
                .addGap(18, 18, 18)
                .addComponent(spinner_productDosePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_dosePeriodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_tittle)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_productName)
                    .addComponent(field_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_productSupplier)
                    .addComponent(combo_productSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_productQuantity)
                    .addComponent(field_productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_productAdmnistrationWay)
                    .addComponent(combo_productAdministrationWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_productSellPrize)
                    .addComponent(field_productSellPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(lbl_productExpirationDate)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_productExpirationDay)
                    .addComponent(spinner_productExpirationDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_productExpirationMonth)
                    .addComponent(spinner_productExpirationMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_productExpirationYear)
                    .addComponent(spinner_productExpirationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lbl_productDose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_productDoseQuantity)
                    .addComponent(spinner_productDoseQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_productDoseQuantityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_productDosePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_dosePeriodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_productDosePeriod))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_productCode))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Register)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void combo_productSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_productSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_productSupplierActionPerformed

    private void combo_productDoseQuantityTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_productDoseQuantityTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_productDoseQuantityTypeActionPerformed

    private void field_productQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_productQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_productQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JComboBox<String> combo_dosePeriodType;
    private javax.swing.JComboBox<String> combo_productAdministrationWay;
    private javax.swing.JComboBox<String> combo_productDoseQuantityType;
    private javax.swing.JComboBox<String> combo_productSupplier;
    private javax.swing.JTextField field_productCode;
    private javax.swing.JTextField field_productName;
    private javax.swing.JTextField field_productQuantity;
    private javax.swing.JTextField field_productSellPrize;
    private javax.swing.JLabel lbl_productAdmnistrationWay;
    private javax.swing.JLabel lbl_productCode;
    private javax.swing.JLabel lbl_productDose;
    private javax.swing.JLabel lbl_productDosePeriod;
    private javax.swing.JLabel lbl_productDoseQuantity;
    private javax.swing.JLabel lbl_productExpirationDate;
    private javax.swing.JLabel lbl_productExpirationDay;
    private javax.swing.JLabel lbl_productExpirationMonth;
    private javax.swing.JLabel lbl_productExpirationYear;
    private javax.swing.JLabel lbl_productName;
    private javax.swing.JLabel lbl_productQuantity;
    private javax.swing.JLabel lbl_productSellPrize;
    private javax.swing.JLabel lbl_productSupplier;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.JSpinner spinner_productDosePeriod;
    private javax.swing.JSpinner spinner_productDoseQuantity;
    private javax.swing.JSpinner spinner_productExpirationDay;
    private javax.swing.JSpinner spinner_productExpirationMonth;
    private javax.swing.JSpinner spinner_productExpirationYear;
    // End of variables declaration//GEN-END:variables
}
