/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.views;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Jorge
 */
public class RegisterSelectionView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterSelection
     */
    public RegisterSelectionView() {
        initComponents();
        radioGroup_value();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup_value = new javax.swing.ButtonGroup();
        radio_valueEmployee = new javax.swing.JRadioButton();
        radio_valueDoctor = new javax.swing.JRadioButton();
        radio_valueSupplier = new javax.swing.JRadioButton();
        radio_valueProduct = new javax.swing.JRadioButton();
        lbl_tittle = new javax.swing.JLabel();
        btn_accept = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radio_valueEmployee.setText("Empleado");
        radio_valueEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_valueEmployeeActionPerformed(evt);
            }
        });

        radio_valueDoctor.setText("Doctor");
        radio_valueDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_valueDoctorActionPerformed(evt);
            }
        });

        radio_valueSupplier.setText("Proveedor");

        radio_valueProduct.setText("Producto");

        lbl_tittle.setText("Registro");

        btn_accept.setText("Aceptar");

        btn_cancel.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_tittle)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cancel)
                        .addGap(71, 71, 71)
                        .addComponent(btn_accept)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_valueEmployee)
                    .addComponent(radio_valueProduct)
                    .addComponent(radio_valueDoctor)
                    .addComponent(radio_valueSupplier))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_tittle)
                .addGap(43, 43, 43)
                .addComponent(radio_valueEmployee)
                .addGap(18, 18, 18)
                .addComponent(radio_valueDoctor)
                .addGap(18, 18, 18)
                .addComponent(radio_valueSupplier)
                .addGap(18, 18, 18)
                .addComponent(radio_valueProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_valueDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_valueDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_valueDoctorActionPerformed

    private void radio_valueEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_valueEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_valueEmployeeActionPerformed
    
    private void radioGroup_value(){
        ButtonGroup bg1 = radioGroup_value;
        bg1.add(radio_valueDoctor);
        bg1.add(radio_valueEmployee);
        bg1.add(radio_valueSupplier);
        bg1.add(radio_valueProduct);
    }
    
    public int getRadioGroupValue(){
        
        if(radio_valueEmployee.isSelected()){
            return 1;
        }
        if(radio_valueDoctor.isSelected()){
            return 2;
            
        }
        if(radio_valueSupplier.isSelected()){
            return 3;
            
        }
        if(radio_valueProduct.isSelected()){
            return 4;
        }
        
        return 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterSelectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterSelectionView().setVisible(true);
            }
        });
        
       
    }

    public JButton getBtn_accept() {
        return btn_accept;
    }

    public void setBtn_accept(JButton btn_accept) {
        this.btn_accept = btn_accept;
    }

    public JButton getBtn_cancel() {
        return btn_cancel;
    }

    public void setBtn_cancel(JButton btn_cancel) {
        this.btn_cancel = btn_cancel;
    }

    public JLabel getLbl_tittle() {
        return lbl_tittle;
    }

    public void setLbl_tittle(JLabel lbl_tittle) {
        this.lbl_tittle = lbl_tittle;
    }

    public ButtonGroup getRadioGroup_value() {
        return radioGroup_value;
    }

    public void setRadioGroup_value(ButtonGroup radioGroup_value) {
        this.radioGroup_value = radioGroup_value;
    }

    public JRadioButton getRadio_valueDoctor() {
        return radio_valueDoctor;
    }

    public void setRadio_valueDoctor(JRadioButton radio_valueDoctor) {
        this.radio_valueDoctor = radio_valueDoctor;
    }

    public JRadioButton getRadio_valueEmployee() {
        return radio_valueEmployee;
    }

    public void setRadio_valueEmployee(JRadioButton radio_valueEmployee) {
        this.radio_valueEmployee = radio_valueEmployee;
    }

    public JRadioButton getRadio_valueProduct() {
        return radio_valueProduct;
    }

    public void setRadio_valueProduct(JRadioButton radio_valueProduct) {
        this.radio_valueProduct = radio_valueProduct;
    }

    public JRadioButton getRadio_valueSupplier() {
        return radio_valueSupplier;
    }

    public void setRadio_valueSupplier(JRadioButton radio_valueSupplier) {
        this.radio_valueSupplier = radio_valueSupplier;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JLabel lbl_tittle;
    private javax.swing.ButtonGroup radioGroup_value;
    private javax.swing.JRadioButton radio_valueDoctor;
    private javax.swing.JRadioButton radio_valueEmployee;
    private javax.swing.JRadioButton radio_valueProduct;
    private javax.swing.JRadioButton radio_valueSupplier;
    // End of variables declaration//GEN-END:variables
}
